name: Release

on:
  push:
    branches:
      - main

jobs:
  docker-publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args:
            - NEXT_PUBLIC_BASE_URL: ${{ secrets.WEB_BASE_URL }}
            - NEXT_PUBLIC_API_BASE_URL: ${{ secrets.API_BASE_URL }}
            - NEXT_PUBLIC_STORAGE_URL: ${{ secrets.STORAGE_URL }}
          push: true
          platforms: linux/amd64
          tags: ghcr.io/dooleyonline/frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
